---
version: "3"

services:
  # host: localhost, port: 1433, user: sa, password Password!1, database: master
  sqlserver:
    image: "microsoft/mssql-server-linux:2017-GA"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      SA_PASSWORD: 'Password!1'
    volumes:
      - ./001_create_database_and_user.sql:/home/001_create_database_and_user.sql
      # host: localhost, port: 1433, user: family, password: Password!1, database: people
      - ./002_create_schema.sql:/home/002_create_schema.sql
    ports:
      - "1433:1433"
