---
version: "3"

services:
  # host: localhost, port: 1433, user: sa, password Password1!, database: master
  sqlserver:
    image: "microsoft/mssql-server-linux:2017-CU8"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      SA_PASSWORD: 'Password1!'
    volumes:
      - ./001_create_database_and_users.sql:/home/001_create_database_and_users.sql
      # host: localhost, port: 1433, user: family_ddl, password: Password1!, database: people
      - ./002_create_schema.sql:/home/002_create_schema.sql
      # host: localhost, port: 1433, user: family_dml, password: Password1!, database: people
      - ./003_test_dml.sql:/home/003_test_dml.sql
    ports:
      - "1433:1433"
