---
version: "3"

services:
  # host: localhost, port: 5432, user: postgres, password: Password1!, database: postgres
  postgres:
    image: "postgres:10.4"
    environment:
      POSTGRES_PASSWORD: 'Password1!'
    volumes:
      - ./.pgpass:/home/.pgpass
      # host: localhost, port: 5432, user: keycloak, password: Password1!, database: keycloak
      - ./postgres_create_database_and_users.sql:/home/postgres_create_database_and_users.sql
    ports:
      - "5432:5432"
