error_format = "$full_error_message"

[theme]
theme = "plain"
[theme.overrides]
separator = ""
idle_bg = "#0F0E1C"
idle_fg = "#D2D4F6"
info_bg = "#0044AA"
info_fg = "#D2D4F6"
good_bg = "#005500"
good_fg = "#D2D4F6"
warning_bg = "#C83737"
warning_fg = "#D2D4F6"
critical_bg = "#D40055"
critical_fg = "#D2D4F6"

[[block]]
block = "cpu"
interval = 2
format = " Pr $utilization.eng(w:1) "

[[block]]
block = "memory"
interval = 4
format = " Me $mem_used_percents.eng(w:1) "

[[block]]
block = "custom_dbus"
path = "/kblay"
format = " $short_text "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d %b %H:%M:%S') "
