error_format = "$full_error_message"

[theme]
theme = "plain"
[theme.overrides]
separator = ""
idle_bg = "#0F0E1C"
idle_fg = "#D2D4F6"

[[block]]
block = "cpu"
interval = 2
format = " P $utilization.eng(w:1) "

[[block]]
block = "memory"
interval = 4
format = " M $mem_used_percents.eng(w:1) "

[[block]]
block = "custom_dbus"
path = "/kblayout"
format = " $short_text "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d %b %H:%M:%S') "
