error_format = "$full_error_message"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = " "

# [icons]
# icons = "awesome6"

[[block]]
block = "cpu"
interval = 2
format = " P $utilization "

[[block]]
block = "memory"
interval = 4
format = " M $mem_used_percents "

[[block]]
block = "custom_dbus"
path = "/kblayout"
format = " $short_text "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d %b %H:%M:%S') "
