icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = " "

[icons]
icons = "awesome4"

[[block]]
block = "cpu"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
