[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = " "

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization "

[[block]]
block = "memory"
interval = 4
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
interval = 60
format = " $icon $available "

[[block]]
block = "net"
interval = 2
format = " $icon $speed_down.eng(prefix:M)/$speed_up.eng(prefix:M) "

[[block]]
block = "time"
format = " $timestamp.datetime(f:'%a %d %b %H:%M:%S') "
interval = 1
