[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = " "

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization "
[block.icons_overrides]
cpu = "\uf2db"

[[block]]
block = "memory"
interval = 4
format = " $icon $mem_used_percents "
[block.icons_overrides]
memory_mem = "\uf7c2"

[[block]]
block = "net"
interval = 4
format = " ^icon_net_down $speed_down.eng(prefix:M,hide_unit:true) ^icon_net_up $speed_up.eng(prefix:M,hide_unit:true) "
[block.icons_overrides]
net_down = "\uf063"
net_up = "\uf062"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d %b %H:%M:%S') "
