error_format = "$full_error_message"

[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = " "

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
interval = 2
format = " $icon $utilization "
[block.icons_overrides]
cpu = "\uf2db"

[[block]]
block = "memory"
interval = 4
format = " $icon $mem_used_percents "
[block.icons_overrides]
memory_mem = "\uf7c2"

[[block]]
block = "custom_dbus"
path = "/kblayout"
format = " $short_text "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d %b %H:%M:%S') "
