pipeline {
    agent any

    stages {

        stage("Bootstrap") {
            steps {
                echo "Bootstrapping..."
                sh "./bin/bootstrap.sh"
            }
        }

        stage("Analyze") {
            steps {
                echo "Analyzing..."
                sh "./bin/analyze.sh"
            }
        }

        stage("Test") {
            steps {
                echo "Testing..."
                sh "./bin/test.sh"
            }
        }
    }

    post {

        success {
            echo "Success"
        }

        failure {
            echo "Failure"
        }
    }
}
