---
- name: Create directories in {{ emacs_home }} for extensions from EmacsWiki
  file: path={{ emacs_home }}/{{ item | basename }} state=directory
  with_items: "{{ emacs_extensions_emacswiki }}"

- name: Install Emacs extensions from EmacsWiki into {{ emacs_home }}
  get_url:
    url: "{{ item }}"
    dest: "{{ emacs_home }}/{{ item | basename }}/{{ item | basename }}"
  with_items: "{{ emacs_extensions_emacswiki }}"

- name: Install Emacs extensions from GitHub into {{ emacs_home }}
  git:
    repo: "{{ item }}"
    dest: "{{ emacs_home }}/{{ item | basename | regex_replace('\\.git$', '') }}"
  with_items: "{{ emacs_extensions_github }}"

- name: Compile Emacs extensions in {{ emacs_home }}
  shell: >
    emacs --batch -Q
    -L {{ emacs_home }}/epl
    -L {{ emacs_home }}/pkg-info.el
    -L {{ emacs_home }}/goto-chg.el
    -L {{ emacs_home }}/key-chord.el
    -L {{ emacs_home }}/s.el
    -L {{ emacs_home }}/dash.el
    -L {{ emacs_home }}/emacs-async
    -L {{ emacs_home }}/exec-path-from-shell
    -L {{ emacs_home }}/zenburn-emacs
    -L {{ emacs_home }}/rainbow-delimiters
    -L {{ emacs_home }}/powerline
    -L {{ emacs_home }}/spaceline
    -L {{ emacs_home }}/smartparens
    -L {{ emacs_home }}/helm
    -L {{ emacs_home }}/emacs-helm-ag
    -L {{ emacs_home }}/company-mode
    -L {{ emacs_home }}/avy
    -L {{ emacs_home }}/kotlin-mode
    -L {{ emacs_home }}/js2-mode
    -L {{ emacs_home }}/web-mode
    -L {{ emacs_home }}/emmet-mode
    -L {{ emacs_home }}/markdown-mode
    -L {{ emacs_home }}/yaml-mode
    -L {{ emacs_home }}/dockerfile-mode
    -L {{ emacs_home }}/evil
    -L {{ emacs_home }}/evil-surround
    -L {{ emacs_home }}/evil-nerd-commenter
    -f batch-byte-compile {{ emacs_home }}/{{ item }}/*.el
  with_items:
    - epl
    - pkg-info.el
    - goto-chg.el
    - key-chord.el
    - s.el
    - dash.el
    - emacs-async
    - exec-path-from-shell
    - zenburn-emacs
    - rainbow-delimiters
    - powerline
    - spaceline
    - smartparens
    - emacs-helm-ag
    - company-mode
    - avy
    - kotlin-mode
    - js2-mode
    - web-mode
    - emmet-mode
    - markdown-mode
    - yaml-mode
    - dockerfile-mode
    - evil-nerd-commenter

- name: Make Emacs extensions in {{ emacs_home }}
  shell: EMACSLOADPATH="{{ emacs_home }}/emacs-async:" make
  args:
    chdir: "{{ emacs_home }}/{{ item }}/"
  with_items:
    - helm
    - evil
    - evil-surround
