---
- name: Create directory ~/local/bin
  file: path=~/local/bin state=directory

- name: Install docker-compose from GitHub into ~/local/bin
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: ~/local/bin/docker-compose
    mode: 0755
