---
version: "3"

services:
  # host: localhost, port: 1433, user: sa, password Password!1, database: master
  sqlserver:
    image: "microsoft/mssql-server-linux:2017-GA"
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: 'Password!1'
    # volumes:
    #   # host: localhost, port: 1433, user: family, password: Password!1, database: people
    #   - ./init_database.sql:/init.sql/init_database.sql
    #   - ./init.sh:/init.sql/init.sh
    # command: ["/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "'Password!1'", "-d", "master", "-i", "/init.sql/init_database.sql"]
    #   - /init.sql/init.sh
    #   - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Password!1' -d master -i /init.sql/init_database.sql
    #   - ["/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "'Password!1'", "-d", "master", "-i", "/init.sql/init_database.sql"]
    ports:
      - "1433:1433"
    restart: always
