version: "3.9"
networks:
  prometheus:
    driver: bridge
services:
  prometheus:
    image: bitnami/prometheus:2.35.0
    volumes:
      - type: bind
        source: prometheus-config.yaml
        target: /opt/bitnami/prometheus/conf/prometheus.yml
        read_only: true
    ports:
      - 9090:9090
  node-exporter:
    image: bitnami/node-exporter:1.3.1
    ports:
      - 9100:9100
