---
#- name: Install Zsh package
#  apt: name=zsh state=latest
#  become: yes

#- name: Change shell to Zsh
#  shell: chsh -s $(which zsh)
#  become: yes

- name: Configure Zsh
  copy: src=.zshrc dest=~

- name: Install Zsh extensions
  git:
    repo: "{{ item }}"
    dest: "{{ zsh_extension_home }}/{{ item | basename | regex_replace('\\.git$', '') }}"
  with_items: "{{ zsh_extensions }}"
