apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: timeseries
    user: postgres
    # secureJsonData:
    #   password:
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: true
    isDefault: true
