version: "3.9"
networks:
  timescaledb:
    driver: bridge
services:
  timescaledb:
    # psql -h localhost -U postgres
    # CREATE DATABASE timeseries;
    # psql -h localhost -U postgres -d timeseries
    image: timescale/timescaledb:2.6.1-pg14
    environment:
      - POSTGRES_PASSWORD=vlad
    ports:
      - 5432:5432
