version: "3.9"
networks:
  timescaledb:
    driver: bridge
services:
  timescaledb:
    # psql -h localhost -U postgres
    # CREATE DATABASE timeseries;
    # psql -h localhost -U postgres -d timeseries
    # psql -h localhost -U postgres -d timeseries -f timeseries.sql \
    #   -Xq -v ON_ERROR_STOP=on -P linestyle=unicode
    image: timescale/timescaledb:2.6.1-pg14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      # - POSTGRES_PASSWORD=vlad
    ports:
      - 5432:5432
