---
- name: Copy .editorconfig into ~
  copy: src=.editorconfig dest=~

- name: Create directory ~/.ptpython
  file: path=~/.ptpython state=directory mode=755

- name: Copy config.py into ~/.ptpython
  copy: src=ptpython_config.py dest=~/.ptpython/config.py
