version: "3.9"
networks:
  prometheus:
    driver: bridge
services:
  prometheus:
    # Take TSDB snapshot
    # curl -X POST http://localhost:9090/api/v1/admin/tsdb/snapshot
    image: bitnami/prometheus:2.35.0
    command:
      - "--config.file=/opt/bitnami/prometheus/conf/prometheus.yml"
      - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
      - "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries"
      - "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
      - "--web.enable-admin-api"
    volumes:
      - type: bind
        source: prometheus-config.yaml
        target: /opt/bitnami/prometheus/conf/prometheus.yml
        read_only: true
      - type: bind
        # source: /home/vlad/Downloads/IPF/snapshots/20220427T031917Z-363053d23320dd99
        source: /home/vlad/Downloads/IPF/snapshots/20220629T211723Z-096d8dcda71f3bdc
        target: /opt/bitnami/prometheus/data
    ports:
      - 9090:9090

  # node-exporter:
  #   image: bitnami/node-exporter:1.3.1
  #   ports:
  #     - 9100:9100

  # grafana:
  #   image: bitnami/grafana:8.5.1
  #   volumes:
  #     - type: bind
  #       source: grafana-config.ini
  #       target: /opt/bitnami/grafana/conf/grafana.ini
  #       read_only: true
  #     - type: bind
  #       source: grafana-datasources.yaml
  #       target: /opt/bitnami/grafana/conf/provisioning/datasources/datasources.yaml
  #       read_only: true
  #   ports:
  #     - 3000:3000
