---
- name: Install Git aliases into ~/.gitconfig
  shell: |
    git config --global user.name "Volodymyr Prokopyuk"
    git config --global user.email "volodymyrprokopyuk@gmail.com"
    git config --global push.default simple

    git config --global alias.s "status -sb"
    git config --global alias.d "diff --color-words"
    git config --global alias.dc "diff --color-words --cached"
    git config --global alias.ds "diff --stat"
    git config --global alias.l "log --all --color --graph --abbrev-commit --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"

    git config --global alias.bs "branch -a -vv"
    git config --global alias.rs "remote -v"

    git config --global alias.cl "clone"
    git config --global alias.a "!git add -A && git s"
    git config --global alias.cm "commit"

    git config --global alias.ch "checkout"
    git config --global alias.chb "checkout -b"
