command_timeout = 1500
[character]
success_symbol = "[|>](bold green)"
error_symbol = "[<|](bold red)"
vimcmd_symbol = "[N>](bold yellow)"
vimcmd_visual_symbol = "[V>](bold purple)"
vimcmd_replace_one_symbol = "[R>](bold blue)"
vimcmd_replace_symbol = "[R>](bold blue)"
