CREATE DATABASE people;
\connect people

CREATE SCHEMA family;

CREATE USER family_ddl WITH ENCRYPTED PASSWORD 'Password1!';
GRANT USAGE, CREATE ON SCHEMA family TO family_ddl;

CREATE USER family_dml WITH ENCRYPTED PASSWORD 'Password1!';
GRANT USAGE, CREATE ON SCHEMA family TO family_dml;
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA family TO family_dml;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA family TO family_dml;
ALTER DEFAULT PRIVILEGES IN SCHEMA family GRANT ALL PRIVILEGES ON TABLES TO family_dml;
ALTER DEFAULT PRIVILEGES IN SCHEMA family GRANT ALL PRIVILEGES ON SEQUENCES TO family_dml;
