---
version: "3"

services:
  # host: localhost, port: 5432, user: postgres, password: Password1!, database: postgres
  postgres:
    image: "postgres:10.4"
    environment:
      POSTGRES_PASSWORD: 'Password1!'
    volumes:
      - ./.pgpass:/home/.pgpass
      - ./001_create_database_and_users.sql:/home/001_create_database_and_users.sql
      # host: localhost, port: 5432, user: family_ddl_dml, password: Password1!, database: people
      - ./002_create_schema.sql:/home/002_create_schema.sql
      - ./003_test_dml.sql:/home/003_test_dml.sql
    ports:
      - "5432:5432"
